### ISSUE TITLE
argparser blows up on python 3

### ISSUE THREAD

**Issue by alex-luminal** [LuminalOSS/credstash#34]
Running `credstash.py` using python 3 produces this stacktrace:
```
⌁ [alex:~/code/credstash] master ± python --version
Python 3.4.3
⌁ [alex:~/code/credstash] master ± python ./credstash.py
Traceback (most recent call last):
  File "./credstash.py", line 482, in <module>
    main()
  File "./credstash.py", line 401, in main
    if args.action == "delete":
AttributeError: 'Namespace' object has no attribute 'action'
```

Runs fine on 2.x.

**Comment by alex-luminal** [comment]
sort of hacky fix in f74b0597bc50fbabd36cd06149ce230bb9796a69
